#!/bin/bash

# Script to package coverage reports into a zip file

OUTPUT_DIR="dist"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
ZIP_FILE="coverage-report-${TIMESTAMP}.zip"

echo "📊 Packaging coverage reports..."
echo ""

# Create output directory
mkdir -p "${OUTPUT_DIR}"

# Create temporary directory for packaging
TEMP_DIR=$(mktemp -d)
echo "📦 Created temporary directory: ${TEMP_DIR}"

# Copy coverage files
echo "📋 Copying coverage HTML reports..."
if [ -d "coverage" ]; then
    cp -r "coverage" "${TEMP_DIR}/"
    echo "  ✓ HTML coverage directory copied"
else
    echo "  ⚠️  Warning: coverage/ directory not found"
fi

echo "📋 Copying coverage XML reports..."
if [ -f "coverage.xml" ]; then
    cp "coverage.xml" "${TEMP_DIR}/"
    echo "  ✓ coverage.xml copied"
else
    echo "  ⚠️  Warning: coverage.xml not found"
fi

if [ -d "coverage_single" ]; then
    cp -r "coverage_single" "${TEMP_DIR}/"
    echo "  ✓ coverage_single directory copied"
else
    echo "  ⚠️  Warning: coverage_single/ directory not found"
fi

# Create a README for the coverage package
cat > "${TEMP_DIR}/COVERAGE_README.md" << 'EOF'
# Coverage Reports Package

This package contains code coverage reports generated by PHPUnit.

## Contents

- `coverage/` - HTML coverage reports (open `index.html` in browser)
- `coverage.xml` - Clover XML coverage report (for SonarCloud)
- `coverage_single/` - Individual file XML coverage reports

## Viewing HTML Coverage

1. Extract this zip file
2. Open `coverage/index.html` in your web browser
3. Navigate through the files to see coverage details

## Coverage Metrics

- **Green lines** = Covered by tests
- **Red lines** = Not covered by tests
- **Yellow lines** = Partially covered

## Using with SonarCloud

The `coverage.xml` file is compatible with SonarCloud. Upload it or configure your CI/CD pipeline to send it to SonarCloud.
EOF

# Create zip file
echo "📦 Creating zip file..."
cd "${TEMP_DIR}"
zip -r "${ZIP_FILE}" . -q
cd - > /dev/null

# Move zip to output directory
mv "${TEMP_DIR}/${ZIP_FILE}" "${OUTPUT_DIR}/"

# Clean up temporary directory
rm -rf "${TEMP_DIR}"

# Get file size
FILE_SIZE=$(du -h "${OUTPUT_DIR}/${ZIP_FILE}" | cut -f1)

echo ""
echo "✅ Coverage package created successfully!"
echo "📁 Output: ${OUTPUT_DIR}/${ZIP_FILE}"
echo "📊 Size: ${FILE_SIZE}"
echo ""
echo "📝 This package includes:"
if [ -d "coverage" ]; then
    echo "   ✓ HTML coverage reports (coverage/)"
fi
if [ -f "coverage.xml" ]; then
    echo "   ✓ XML coverage report (coverage.xml)"
fi
if [ -d "coverage_single" ]; then
    echo "   ✓ Single file XML reports (coverage_single/)"
fi
echo ""
echo "🚀 To view HTML coverage:"
echo "   1. Extract the zip file"
echo "   2. Open coverage/index.html in your browser"
echo ""

