name: Run Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, xml, dom, curl, libxml, iconv, zip
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader

      - name: Run PHPUnit tests
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.xml --log-junit=phpunit-report.xml || echo "Tests completed with errors, but continuing..."
          # Check if coverage was generated even if tests failed
          if [ -f coverage.xml ]; then
            echo "✅ coverage.xml generated successfully"
          fi
        continue-on-error: true

      - name: Upload coverage to artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: |
            coverage.xml
            phpunit-report.xml
            coverage/

